---
- name: My filebeat
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Install filebeat
    yum:
      name:  "filebeat-{{ filebeat_version|default('*') }}"
      state: present

  - name: Enable filebeat
    systemd:
        name: filebeat
        state: restarted   
        enabled: yes  

  - name: FILEBEAT - Copy base filebeat config file  
    shell: "cp src=/srv/ansible/setup-files/filebeat/filebeat.yml dest=/etc/filebeat/filebeat.yml"
    
