---
- hosts: localhost
  vars_files: 
  - us-east-1.yaml
  tasks: 
  - name: Create instance
    ec2:
      key_name: "{{key_name}}"
      instance_type: "{{instance_type}}"
      image: "{{image}}"
      group: "{{group}}"
      count: "{{count}}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      assign_public_ip: "{{assign_public_ip}}"
      region: "{{region}}"